name: yashwanth

on: [push,pull_request]

jobs:
  yashwanth:
    name: yashwanth234
    runs-on: ubuntu-latest
    steps:
      - name: checkout my code 
        uses: actions/checkout@v2
      
      - name: Run super-linter
        uses: github/super-linter@v4
        env:
         DEFAULT_BRANCH: main
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
